### ISSUE TITLE
load entire glyph cache at once

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_Bitmap_Font#1]
having to seek thru a 20-50K file one-per-char takes 1-2 seconds per glyph. if your first string has a bunch of chars it takes 20-30 seconds. good news is it works, but makes workflow sluggish. if we're going to keep it in python, lets have a way cache/load the whole font into memory upon request. e.g. `font = bitmap_font.load_font("fonts/Checkbook-25.bdf", load_all=True)`

**Comment by tannewt** [comment]
Done in 6beb2162e47b3bddde3ce8668428e4f14232737b. You can now call `load_glyphs` with a sequence (string, list or set) to pre-load.
