### ISSUE TITLE
PyPI installation only downloading *.egg-info directory

### ISSUE THREAD

**Issue by andreamah** [adafruit/Adafruit_CircuitPython_Bitmap_Font#18]
Hi! 

When I try to download this library using `pip3 install adafruit-circuitpython-bitmap_font`, I only receive the `adafruit_circuitpython_bitmap_font-1.0.5-py3.8.egg-info` folder at my `<virtual_env_root>/Libs/site-packages` (with all of the dependencies). However, shouldn't I also get another directory called `adafruit_bitmap_font`?

I found that if I download the `adafruit-circuitpython-bitmap_font-1.0.5.tar.gz` directly from PyPI, unzip, then remove `setup.cfg`, then I can pip install from that properly. Could this have to do with the issue that I was experiencing?

Thanks!

**Comment by andreamah** [comment]
UPDATE: I found that if I change `py_modules` to `packages` in the last line of `setup.py` in the tar.gz from PyPI, I can install directly from the tar.gz without unzipping it. Could this be the issue?

**Comment by tannewt** [comment]
@andreamah That does sound like an issue. Mind making a PR to fix it?

**Comment by kattni** [comment]
Fixed! Thanks again!
