### ISSUE TITLE
print(font.get_glyph(ord("A"))) ?

### ISSUE THREAD

**Issue by vldmr-d** [adafruit/Adafruit_CircuitPython_Bitmap_Font#53]
print(font.get_glyph(ord("A"))) ?
output
<fontio.Glyph object at 0x7fc877e45d90>

**Comment by FoamyGuy** [comment]
Sorry, it's unclear what issue you are reporting. Please reach out on the forums or Discord if you need support. If you are reporting a problem with the library please include more details.
