### ISSUE TITLE
Add option for configurable bounding box line search limit

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Bitmap_Font#55]
I recently had an issue where a BDF font file had a long license commented at the start, so this library would error out trying to initialize it.  It was fixed by moving the license out of the file, but a configurable limit of lines to search for the bounding box parameter would prevent this issue.  Not sure how either removing or increasing the limit would affect things like speed, however.

**Comment by FoamyGuy** [comment]
This might have been the same issue that #48 was attempting to solve. I couldn't get the changes from that PR working and the person who made it never did respond. 

If you're interested in looking into this, it may be worth starting from the branch from that PR if it's still around.

**Comment by tekktrik** [comment]
Ah, good catch!  Sure, let me take a look!

**Comment by tekktrik** [comment]
Ah, I think I see the problem - the PR branch only reads the next line when the current one it sees is a COMMENT.  If there's anything between a COMMENT and a FONTBOUNDINGBOX parameter, it will never reach it.  It can be fixed by making sure the next line is read in every loop iteration.  Thanks again!

**Comment by FoamyGuy** [comment]
resolved by #56
