### ISSUE TITLE
Remove backward-compatible imports when 4.0.0 released

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bitmap_Font#9]
Remove the `try`-`import` code that supports older versions of `displayio` et al when 4.0.0 is released as stable.

**Comment by kattni** [comment]
If you are completely new to this and would like to try to fix this issue, please ping me here or visit us in the [Adafruit Discord #circuitpython channel](https://adafru.it/discord) and we can help you through it.

**Comment by kattni** [comment]
Fixed in #21
